<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Price</h1>

<form class="pure-form" method="post" action="/price/new">
    <label for="title">Title</label>
    <input name="title" id="title" type="text" size="60" /><br />
    <label for="Price">Price</label>
    <input type="number" name="price" id="price" /><br />
    <label for="description">Description</label>
    <textarea name="description" id="description" rows="6" cols="80"></textarea><br />
    <br />
    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>


