version: "3"
services:
    nginx:
        image: nginx:stable
        volumes:
            - ./docker-nginx.conf:/etc/nginx/nginx.conf
            - ${PWD}/landingpage:/var/www/html/landingpage
            - ${PWD}/boxbilling:/var/www/html/boxbilling
        ports:
            - 8081:8081
            - 8004:8082
        networks:
            backend:
    landingpage:
        build:
            context: ./landingpage
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/landingpage:/var/www/html
        environment:
            DB_HOST: 'mysql'
            DB_NAME: 'landingpageDb'
            DB_USER: 'root'
            DB_PASS: 'password123'
            DB_PORT: '3306'
        networks:
            backend:
        depends_on:
            - mysql
        # restart: always
    boxbilling:
        build:
            context: ./boxbilling
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/boxbilling:/var/www/html
        environment:
            DB_HOST: 'mysql'
            DB_NAME: 'boxbilling'
            DB_USER: 'root'
            DB_PASS: 'password123'
        networks:
            backend:
        depends_on:
            - database
        # restart: mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password123'
            MYSQL_DATABASE: 'landingpageDb'
            MYSQL_USER: 'landingpage'
            MYSQL_PASSWORD: 'password123'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            backend:
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword123"]
            retries: 3
            timeout: 5s
networks:
  backend:
volumes:
    mysql:
        driver: local